### ISSUE TITLE
Error finding the headers

### ISSUE THREAD

**Issue by shuuha** [demchenkoalex/react-native-module-template#15]
Hello.

I have git cloned your repo made the packages installation and opened the ios project in Xcode.
I am getting an error that the ReactBridgeFile was not found. Could you please tell me what I am doing wrong?
Greate appreciate your help.

![Screen Shot 2021-08-11 at 21 36 24](https://user-images.githubusercontent.com/32106081/129068434-41788ac8-90c3-495c-aec1-49e9ad672147.png)

**Comment by demchenkoalex** [comment]
Hey, yes :)

So basically you can't run iOS project as a standalone, since it does not have React dependencies, but you can open the iOS project in the example folder and in that project you will have linked project you try to run (you can find it in the explorer window on the left side of Xcode) and you can modify code/files there, and example will build containing the code you wrote in the library's iOS project :) hopefully this makes sense

**Comment by shuuha** [comment]
Reoping the issue, just came across another irritating problem :)
Though there is no issue in briding file, the .m file is showing up the same error as above.
Any ideas? :)
![Screen Shot 2021-08-11 at 22 12 43](https://user-images.githubusercontent.com/32106081/129074085-0aea228a-d270-4847-bc2f-6c4b7f4b07d8.png)

**Comment by demchenkoalex** [comment]
Hmm that worked previously :) will take a look when back

**Comment by demchenkoalex** [comment]
Now with a bigger screen I can see that you opened `*.xcodeproj` file, remember when using Cocoapods (which is default in React Native for year+ now)  you need to open `*.xcworkspace` so Cocoapods dependencies (including React) will be available during the build time :) I recommend https://github.com/ohmyzsh/ohmyzsh with an Xcode plugin, this will allow you to run `xc` in the terminal and it will correctly decide whether to open Project or a Workspace, so you don't have to think about it :)

on the side note don't forget to run `yarn` and `npx pod-install` inside the `example` folder too :)

**Comment by shuuha** [comment]
Ok, thank you, seems the issues are resolved. :)
